/**
 * Auto-generated email template
 * Generated at build time from AutoReplyTemplate component
 * DO NOT EDIT THIS FILE MANUALLY - Edit AutoReplyTemplate.tsx and regenerate
 */

export const AUTO_REPLY_TEMPLATE = `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html dir="ltr" lang="en">
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
    <meta name="x-apple-disable-message-reformatting" />
  </head>
  <body
    style="background-color:#f4f4f4;font-family:Arial, sans-serif;color:#333">
    <!--\$--><!--html--><!--head--><!--body-->
    <table
      align="center"
      width="100%"
      border="0"
      cellpadding="0"
      cellspacing="0"
      role="presentation"
      style="max-width:600px;background-color:#ffffff;padding:20px;margin:20px auto;border-radius:8px">
      <tbody>
        <tr style="width:100%">
          <td>
            <h1 style="color:#0e7490;font-size:24px">
              Thank You for Reaching Out, {{NAME}}!
            </h1>
            <p
              style="font-size:16px;line-height:1.5;margin-top:16px;margin-bottom:16px">
              I&#x27;ve received your message and will get back to you as soon
              as possible. I appreciate your interest and look forward to
              connecting!
            </p>
            <hr
              style="width:100%;border:none;border-top:1px solid #eaeaea;border-color:#e5e7eb;margin:20px 0" />
            <p
              style="font-size:14px;line-height:24px;color:#4b5563;margin-top:16px;margin-bottom:16px">
              <strong>Your Message:</strong><br />{{MESSAGE}}
            </p>
            <p
              style="font-size:14px;line-height:24px;margin-top:20px;margin-bottom:16px">
              Best regards,<br />Kevin C. Sclafani (quietghost)<br />
            </p>
          </td>
        </tr>
      </tbody>
    </table>
    <!--/\$-->
  </body>
</html>
`;

/**
 * Replace template placeholders with actual values
 */
export function renderAutoReplyEmail(name: string, message: string): string {
  return AUTO_REPLY_TEMPLATE
    .replace(/{{NAME}}/g, escapeHtml(name))
    .replace(/{{MESSAGE}}/g, escapeHtml(message).replace(/\n/g, '<br>'));
}

/**
 * Escape HTML to prevent XSS
 */
function escapeHtml(text: string): string {
  const map: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;',
  };
  return text.replace(/[&<>"']/g, (char) => map[char] || char);
}
